version: '3'
services:
  frontend:
    build: ./budget_tracker_frontend
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - ./budget_tracker_frontend:/app
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000

  backend:
    build: ./budget_tracker_backend
    command: ["./wait-for-db.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./budget_tracker_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./budget_tracker_backend/budget_tracker_backend/.env
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data:


