name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3]
    services:
      postgres: 
        image: postgres:17
        ports: 
          - 5432:5432
        env:
          POSTGRES_DB: ${{secrets.DB_NAME}}
          POSTGRES_USER: ${{secrets.DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: localhost
      DB_PORT: 5432
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      working-directory: ./budget_tracker_backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file for database
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./budget_tracker_backend/budget_tracker_backend/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> ./budget_tracker_backend/budget_tracker_backend/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./budget_tracker_backend/budget_tracker_backend/.env
        echo "DB_HOST=localhost" >> ./budget_tracker_backend/budget_tracker_backend/.env
        echo "DB_PORT=5432" >> ./budget_tracker_backend/budget_tracker_backend/.env

    - name: Wait for the database to be ready
      working-directory: ./budget_tracker_backend
      run: ./wait-for-db-workflow.sh
        
    - name: Run Tests
      working-directory: ./budget_tracker_backend
      run: |
        python manage.py migrate
        python manage.py test
